version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - C:/xampp/htdocs/crud/nginx:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php

  php:
    image: php:8.1-fpm
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: sistema_telefonico
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"